name: NPM publish

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # The dev tools are needed to package, as we are building before packaging.
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - uses: infrastructure-blocks/npm-publish-from-label-action@v0
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        with:
          github-pat: ${{ secrets.PAT }}
          release-branch: master
